nginx_vhosts:
  - listen: "80"
    server_name: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
    root: "/etc/editor"
    index: "index.html"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "editor.conf"
    extra_parameters: |
      location /api {
          proxy_set_header Host $host;
          proxy_pass_request_headers on;
          proxy_pass_request_body on;
          proxy_redirect off;
          proxy_buffering off;
          proxy_pass http://localhost:8080/api;
      }

      location / {
        index index.html;
        try_files $uri $uri/ /index.html;
      }
