- hosts: pi
  become: true
  roles:
    - role: common
      tags:
        - common
    # - role: audio
    #   tags:
    #     - audio
    - role: Stouts.hostname
      tags:
        - common

    - role: joshualund.golang
      vars:
        # https://golang.org/dl/
        go_tarball: go1.12.linux-armv6l.tar.gz
        go_tarball_checksum: "sha256:ea0636f055763d309437461b5817452419411eb1f598dc7f35999fae05bcb79a"
        go_version_target: "go version go1.12 linux/arm"
        package_arch: arm
      tags:
        - golang

    - role: lae.glide
      tags:
        - golang
        - glide

    - role: controller
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
        GOPATH: "/etc/controller"
      vars:
        controller_base_path: /etc/controller
      tags:
        - controller
        - offline
