- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Ensure that controller_path is set, we need that for the controller service
      fail: msg="Bailing out. Please specify the controller_path."
      when: controller_path|default(None) == None or controller_path == ""
      tags:
        - controller
    
    - debug:
        var: controller_path

    - name: Ensure that definition_files is set, we need that for the controller service
      fail: msg="Bailing out. Please specify the definition_files."
      when: definition_files|default(None) == None or definition_files == ""
      tags:
        - definitions

- hosts: pi
  become: true
  environment:
    PATH: "/opt/glide/linux-armv7:/usr/local/go/bin:{{ ansible_env.PATH }}"
    GOPATH: "/var/controller"
  vars:
    go_tarball: go1.8.3.linux-armv6l.tar.gz
    go_tarball_checksum: "sha256:3c30a3e24736ca776fc6314e5092fb8584bd3a4a2c2fa7307ae779ba2735e668"
    go_version_target: "go version go1.8.3 linux/arm"
    package_arch: arm
    controller_path: "{{ controller_path }}"
    definition_files: "{{ definition_files }}"

  roles:
    - role: common
      tags:
        - common
    - role: audio
      tags:
        - audio
    - role: Stouts.hostname
      tags:
        - common

    - role: joshualund.golang
      tags:
        - golang
    - role: kurtzhong.glide
      tags:
        - golang
        - glide

    - role: definitions
      tags:
        - definitions
    - role: controller
      tags:
        - controller
