---
# tasks file for ansible-glide


- name: Download the installation package
  get_url:
    url: "{{ package_download_url }}"
    dest: "/opt/{{ package_tgz }}"
    validate_certs: no

- name: Create path for unarchiving
  file: path=/opt/{{ package_name }} state=directory

- name: Unarchive the package
  unarchive:
    copy: no
    src: "/opt/{{ package_tgz }}"
    dest: "/opt/{{ package_name }}"

- name: Check the status /opt/glide
  stat: path=/opt/glide
  register: sl_st

- name: Unlink the /opt/glide (if exists already)
  command: unlink /opt/glide
  when: sl_st.stat.islnk is defined and sl_st.stat.islnk == True

- name: Create softlink
  file: src=/opt/{{ package_name }} dest=/opt/glide state=link

- name: Make the binary discoverable accross the sytem
  template: src=etc/profile.d/glide.sh dest=/etc/profile.d/glide.sh owner=root group=root mode=0644
