- name: Print the target dir
  debug:
    msg: "{{ controller_src_path }}"
  tags:
  - always

- name: Create src dir
  file:
    state: directory
    name: "{{ controller_src_path | dirname }}"
  tags:
  - build
  - copy

# Example checkout a github repo and use refspec to fetch all pull requests
- git:
    repo: https://{{ controller_package }}.git
    dest: "{{ controller_src_path }}"

- name: Install dependencies
  command: glide install --strip-vendor
  args:
    chdir: "{{ controller_src_path }}"
  tags:
    - download

- name: Build controller binary
  command: go build -o /etc/controller/bin/controller .
  args:
    chdir: "{{ controller_src_path }}"
  tags:
  - build
