- name: Install required dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - libportmidi-dev
    - portaudio19-dev
    # - midisport-firmware
  tags:
  - controller-dep
  - download
#
# - name: install controller systemd unit file
#   template:
#     src: midisport-firmware.rules
#     dest: /etc/udev/rules.d/99-midisport-firmware.rules
#   tags:
#   - controller-dep

- name: Create controller directory
  file:
    path: /etc/controller/bin
    mode: 0755
    state: directory
    owner: root
    group: root
    recurse: true
  tags:
    - controller-binary

- name: Compile binary
  include_tasks: compile.yml
  tags:
    - controller-binary

- name: install controller systemd unit file
  template:
    src: controller.service
    dest: /etc/systemd/system/controller.service
  tags:
  - controller-systemd

- name: start controller
  systemd:
    state: started
    name: controller
    daemon_reload: yes
  tags:
  - controller-systemd
