- name: Install required dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - libportmidi-dev
    - portaudio19-dev
    # - midisport-firmware
  tags:
  - controller
  - download

# - name: install controller systemd unit file
#   template:
#     src: midisport-firmware.rules
#     dest: /etc/udev/rules.d/99-midisport-firmware.rules
#   tags:
#   - controller

- name: Create controller directory
  file:
    path: /etc/controller/bin
    mode: 0755
    state: directory
    owner: root
    group: root
    recurse: true
  tags:
    - controller

- name: Create storage directory
  file:
    path: /var/controller/storage
    mode: 0755
    state: directory
    owner: root
    group: root
    recurse: true
  tags:
    - controller

- name: Create src dir
  file:
    state: directory
    name: "{{ controller_src_path | dirname }}"
  tags:
  - controller

# Example checkout a github repo and use refspec to fetch all pull requests
- git:
    repo: https://{{ controller_package }}.git
    dest: "{{ controller_src_path }}"
  register: controller_git
  tags:
    - controller

- name: Install dependencies
  command: glide install --strip-vendor
  args:
    chdir: "{{ controller_src_path }}"
  when: controller_git.changed
  tags:
    - controller

- name: Build controller binary
  command: go build -o /etc/controller/bin/controller .
  args:
    chdir: "{{ controller_src_path }}"
  when: controller_git.changed
  notify: controller_restart
  tags:
    - controller

- name: install controller systemd unit file
  template:
    src: controller.service
    dest: /etc/systemd/system/controller.service
  register: controller_systemd.changed
  notify: controller_restart
  tags:
    - controller

- name: start controller
  systemd:
    state: started
    name: controller
    daemon_reload: yes
  when: controller_git.changed
  tags:
    - controller
