---
- name: Packages | Update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Packages | install base pacakges
  apt: name={{ item }}
  with_items:
    - vim
    - htop
    - rsync
    - git-core
