- name: Create group for each user
  group: name="{{ item.name }}"
  with_items: '{{users}}'

- name: Add user for each user
  user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    groups: "sudo,{{ item.name }}"
    state: "present"
    shell: "/bin/bash"
  with_items: '{{users}}'
  notify:
    - Restart ssh

- name: Allow password-less sudo for each user
  lineinfile:
    dest: '/etc/sudoers'
    state: 'present'
    line: '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
  with_items: '{{users}}'
  notify:
    - Restart ssh

- name: Add SSH keys for each user
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items: '{{users}}'
  when: not ansible_check_mode
  notify:
    - Restart ssh
