- name: Update storage repo
  git:
    repo: https://{{ storage_package }}.git
    dest: "{{ storage_path | dirname }}"
  tags:
    - storage

# - name: Set git credential store
#   shell: git config --global credential.helper 'store --file ~/.my-credentials'
